AWSTemplateFormatVersion: '2010-09-09'
Description: Deploy Spark OpenAQ Job with EMR Serverless, Lambda Trigger, S3, Athena, Glue

Parameters:
  BucketName:
    Type: String
    Default: openaq-rahul-bucket-20250629
    Description: S3 bucket name for JAR, mapping JSON, and outputs
  EMRAppName:
    Type: String
    Default: OpenAQEMRApp
  OutputPrefix:
    Type: String
    Default: output/openaq_latest_data/

Resources:

  EMRServerlessExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${AWS::StackName}-EMRExecutionRole"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: emr-serverless.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess

  OpenAQEMRApp:
    Type: AWS::EMRServerless::Application
    Properties:
      Name: !Ref EMRAppName
      ReleaseLabel: emr-6.10.0
      Type: Spark
      MaximumCapacity:
        Cpu: 4 vCPU
        Memory: 8 GB

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${AWS::StackName}-LambdaExecutionRole"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: OpenAQLambdaPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - emr-serverless:StartJobRun
                Resource: '*'
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: '*'
              - Effect: Allow
                Action:
                  - iam:PassRole
                Resource: !GetAtt EMRServerlessExecutionRole.Arn

  TriggerEMRJobLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: TriggerOpenAQJob
      Runtime: python3.9
      Role: !GetAtt LambdaExecutionRole.Arn
      Handler: index.handler
      Timeout: 120
      Code:
        ZipFile: |
          import boto3
          import os
          def handler(event, context):
              client = boto3.client('emr-serverless')
              response = client.start_job_run(
                  applicationId=os.environ['EMR_APP_ID'],
                  executionRoleArn=os.environ['EMR_ROLE'],
                  jobDriver={
                      'sparkSubmit': {
                          'entryPoint': f"s3://{os.environ['BUCKET']}/target/spark-processor-1.0-SNAPSHOT.jar",
                          'entryPointArguments': [],
                          'sparkSubmitParameters': '--class com.openaq.pipeline.OpenAQLatestFetcher'
                      }
                  },
                  configurationOverrides={
                      'monitoringConfiguration': {
                          's3MonitoringConfiguration': {
                              'logUri': f"s3://{os.environ['BUCKET']}/logs/"
                          }
                      },
                      'applicationConfiguration': [
                          {
                              'classification': 'spark-defaults',
                              'properties': {
                                  'spark.driverEnv.OPENAQ_API_KEY': os.environ['OPENAQ_API_KEY'],
                                  'spark.executorEnv.OPENAQ_API_KEY': os.environ['OPENAQ_API_KEY']
                              }
                          }
                      ]
                  }
              )
              return response
      Environment:
        Variables:
          EMR_APP_ID: !Ref OpenAQEMRApp
          EMR_ROLE: !GetAtt EMRServerlessExecutionRole.Arn
          BUCKET: !Ref BucketName
          OPENAQ_API_KEY: bc67d2fd7c804a0d841265db9b2b2561e2e4cdee1a144a4b68684c665b3fc06b

Outputs:
  LambdaFunction:
    Value: !Ref TriggerEMRJobLambda
    Description: Lambda function to trigger the EMR Spark job
  EMRApplicationId:
    Value: !Ref OpenAQEMRApp
    Description: EMR Serverless Application ID
  BucketName:
    Value: !Ref BucketName
    Description: S3 Bucket where files are stored
